# -*- coding: utf-8 -*-
#!/usr/bin/env python3
"""CLI for server MCP server.

Generated by: fastmcp generate-cli server.py
"""

import json
import sys
from typing import Annotated

import cyclopts
import mcp.types
from rich.console import Console

from fastmcp import Client
from fastmcp.client.transports import StdioTransport

# Modify this to change how the CLI connects to the MCP server.
CLIENT_SPEC = StdioTransport(command='fastmcp', args=['run', 'D:\\projects\\PRism\\server.py', '--no-banner'])

app = cyclopts.App(name="server", help="CLI for server MCP server")
call_tool_app = cyclopts.App(name="call-tool", help="Call a tool on the server")
app.command(call_tool_app)

console = Console()


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------


def _print_tool_result(result):
    if result.is_error:
        for block in result.content:
            if isinstance(block, mcp.types.TextContent):
                console.print(f"[bold red]Error:[/bold red] {block.text}")
            else:
                console.print(f"[bold red]Error:[/bold red] {block}")
        sys.exit(1)

    if result.structured_content is not None:
        console.print_json(json.dumps(result.structured_content))
        return

    for block in result.content:
        if isinstance(block, mcp.types.TextContent):
            console.print(block.text)
        elif isinstance(block, mcp.types.ImageContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Image: {block.mimeType}, ~{size} bytes][/dim]")
        elif isinstance(block, mcp.types.AudioContent):
            size = len(block.data) * 3 // 4
            console.print(f"[dim][Audio: {block.mimeType}, ~{size} bytes][/dim]")


async def _call_tool(tool_name: str, arguments: dict) -> None:
    # Filter out None values and empty lists (defaults for optional array params)
    filtered = {
        k: v
        for k, v in arguments.items()
        if v is not None and (not isinstance(v, list) or len(v) > 0)
    }
    async with Client(CLIENT_SPEC) as client:
        result = await client.call_tool(tool_name, filtered, raise_on_error=False)
        _print_tool_result(result)
        if result.is_error:
            sys.exit(1)


# ---------------------------------------------------------------------------
# List / read commands
# ---------------------------------------------------------------------------


@app.command
async def list_tools() -> None:
    """List available tools."""
    async with Client(CLIENT_SPEC) as client:
        tools = await client.list_tools()
        if not tools:
            console.print("[dim]No tools found.[/dim]")
            return
        for tool in tools:
            sig_parts = []
            props = tool.inputSchema.get("properties", {})
            required = set(tool.inputSchema.get("required", []))
            for pname, pschema in props.items():
                ptype = pschema.get("type", "string")
                if pname in required:
                    sig_parts.append(f"{pname}: {ptype}")
                else:
                    sig_parts.append(f"{pname}: {ptype} = ...")
            sig = f"{tool.name}({', '.join(sig_parts)})"
            console.print(f"  [cyan]{sig}[/cyan]")
            if tool.description:
                console.print(f"    {tool.description}")
            console.print()


@app.command
async def list_resources() -> None:
    """List available resources."""
    async with Client(CLIENT_SPEC) as client:
        resources = await client.list_resources()
        if not resources:
            console.print("[dim]No resources found.[/dim]")
            return
        for r in resources:
            console.print(f"  [cyan]{r.uri}[/cyan]")
            desc_parts = [r.name or "", r.description or ""]
            desc = " — ".join(p for p in desc_parts if p)
            if desc:
                console.print(f"    {desc}")
        console.print()


@app.command
async def read_resource(uri: Annotated[str, cyclopts.Parameter(help="Resource URI")]) -> None:
    """Read a resource by URI."""
    async with Client(CLIENT_SPEC) as client:
        contents = await client.read_resource(uri)
        for block in contents:
            if isinstance(block, mcp.types.TextResourceContents):
                console.print(block.text)
            elif isinstance(block, mcp.types.BlobResourceContents):
                size = len(block.blob) * 3 // 4
                console.print(f"[dim][Blob: {block.mimeType}, ~{size} bytes][/dim]")


@app.command
async def list_prompts() -> None:
    """List available prompts."""
    async with Client(CLIENT_SPEC) as client:
        prompts = await client.list_prompts()
        if not prompts:
            console.print("[dim]No prompts found.[/dim]")
            return
        for p in prompts:
            args_str = ""
            if p.arguments:
                parts = [a.name for a in p.arguments]
                args_str = f"({', '.join(parts)})"
            console.print(f"  [cyan]{p.name}{args_str}[/cyan]")
            if p.description:
                console.print(f"    {p.description}")
        console.print()


@app.command
async def get_prompt(
    name: Annotated[str, cyclopts.Parameter(help="Prompt name")],
    *arguments: str,
) -> None:
    """Get a prompt by name. Pass arguments as key=value pairs."""
    parsed: dict[str, str] = {}
    for arg in arguments:
        if "=" not in arg:
            console.print(f"[bold red]Error:[/bold red] Invalid argument {arg!r} — expected key=value")
            sys.exit(1)
        key, value = arg.split("=", 1)
        parsed[key] = value

    async with Client(CLIENT_SPEC) as client:
        result = await client.get_prompt(name, parsed or None)
        for msg in result.messages:
            console.print(f"[bold]{msg.role}:[/bold]")
            if isinstance(msg.content, mcp.types.TextContent):
                console.print(f"  {msg.content.text}")
            elif isinstance(msg.content, mcp.types.ImageContent):
                size = len(msg.content.data) * 3 // 4
                console.print(f"  [dim][Image: {msg.content.mimeType}, ~{size} bytes][/dim]")
            else:
                console.print(f"  {msg.content}")
            console.print()


# ---------------------------------------------------------------------------
# Tool commands (generated from server schema)
# ---------------------------------------------------------------------------

@call_tool_app.command(name='authenticate')
async def authenticate(
    *,
    token: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Authenticate with GitHub using a Personal Access Token (PAT).
Call this when the user wants to connect their GitHub account
or switch to a different token.
Returns the authenticated username on success.'''
    await _call_tool('authenticate', {'token': token})


@call_tool_app.command(name='list_repos')
async def list_repos(
    *,
    sort: Annotated[str, cyclopts.Parameter(help="")] = 'updated',
    repo_type: Annotated[str, cyclopts.Parameter(help="")] = 'all',
    limit: Annotated[int, cyclopts.Parameter(help="")] = 30,
) -> None:
    '''Lists all GitHub repositories accessible to the authenticated user.
Call this when the user asks about their repos, projects, or codebases.'''
    await _call_tool('list_repos', {'sort': sort, 'repo_type': repo_type, 'limit': limit})


@call_tool_app.command(name='get_open_issues')
async def get_open_issues(
    *,
    repo: Annotated[str, cyclopts.Parameter(help="")],
    branch: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    milestone: Annotated[str | None, cyclopts.Parameter(help="JSON Schema: {\n                            \"anyOf\": [\n                              {\n                                \"type\": \"string\"\n                              },\n                              {\n                                \"type\": \"null\"\n                              }\n                            ],\n                            \"default\": null\n                          }")] = None,
    state: Annotated[str, cyclopts.Parameter(help="")] = 'open',
    limit: Annotated[int, cyclopts.Parameter(help="")] = 30,
) -> None:
    '''Get general open issues for a GitHub repository.

Call this when the user asks for a list of open bugs, tasks, or issues on a repo.
IMPORTANT: DO NOT use this tool if the user asks for issues linked to a specific git branch. 
If they mention a branch, use the `branch_tickets` tool instead.'''
    # Parse JSON parameters
    branch_parsed = json.loads(branch) if isinstance(branch, str) else branch
    milestone_parsed = json.loads(milestone) if isinstance(milestone, str) else milestone

    await _call_tool('get_open_issues', {'repo': repo, 'branch': branch_parsed, 'milestone': milestone_parsed, 'state': state, 'limit': limit})


@call_tool_app.command(name='branch_tickets')
async def branch_tickets(
    *,
    repo: Annotated[str, cyclopts.Parameter(help="")],
    branch_name: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Find specific tickets or issues that are linked to a given branch_name.

USE THIS TOOL (instead of get_open_issues) whenever the user asks about issues connected, 
linked, or related to a branch name. It performs a deep search across issue bodies and labels.'''
    await _call_tool('branch_tickets', {'repo': repo, 'branch_name': branch_name})


@call_tool_app.command(name='get_my_prs')
async def get_my_prs(
    *,
    state: Annotated[str, cyclopts.Parameter(help="")] = 'open',
    limit: Annotated[int, cyclopts.Parameter(help="")] = 30,
) -> None:
    '''Get pull requests where the authenticated user is the author or assignee.
Searches across ALL repos — not limited to a single repo.

Call this when the user asks about their PRs, pull requests, or code reviews.
For example: "What PRs do I have open?", "Show my merged PRs".'''
    await _call_tool('get_my_prs', {'state': state, 'limit': limit})


@call_tool_app.command(name='get_pr_diff')
async def get_pr_diff(
    *,
    repo: Annotated[str, cyclopts.Parameter(help="")],
    pr_number: Annotated[int, cyclopts.Parameter(help="")],
    max_lines: Annotated[int, cyclopts.Parameter(help="")] = 500,
) -> None:
    '''Get the raw unified diff for a pull request.
Call this when the user asks to see what changes are in a PR,
or wants you to summarize or review a PR.
Returns the diff as a string (truncated if it exceeds max_lines).'''
    await _call_tool('get_pr_diff', {'repo': repo, 'pr_number': pr_number, 'max_lines': max_lines})


@call_tool_app.command(name='review_pr')
async def review_pr(
    *,
    repo: Annotated[str, cyclopts.Parameter(help="")],
    pr_number: Annotated[int, cyclopts.Parameter(help="")],
) -> None:
    '''Review a pull request by analyzing its raw diff.
Returns a summary, risk flags, and suggested reviewers.'''
    await _call_tool('review_pr', {'repo': repo, 'pr_number': pr_number})


@call_tool_app.command(name='ci_status')
async def ci_status(
    *,
    repo: Annotated[str, cyclopts.Parameter(help="")],
    pr_number: Annotated[int, cyclopts.Parameter(help="")],
) -> None:
    '''Check the GitHub Actions CI run status for a Pull Request.
Returns a minimal combined state like \'success\', \'pending\', or \'failure\'.'''
    await _call_tool('ci_status', {'repo': repo, 'pr_number': pr_number})


@call_tool_app.command(name='comment_on_pr')
async def comment_on_pr(
    *,
    repo: Annotated[str, cyclopts.Parameter(help="")],
    pr_number: Annotated[int, cyclopts.Parameter(help="")],
    body: Annotated[str, cyclopts.Parameter(help="")],
) -> None:
    '''Post a review comment on a pull request.
Use this to provide feedback, ask questions, or summarize findings on a PR.'''
    await _call_tool('comment_on_pr', {'repo': repo, 'pr_number': pr_number, 'body': body})


@call_tool_app.command(name='assign_reviewer')
async def assign_reviewer(
    *,
    repo: Annotated[str, cyclopts.Parameter(help="")],
    pr_number: Annotated[int, cyclopts.Parameter(help="")],
) -> None:
    '''Automatically determine and assign the best reviewer(s) for a PR based on file commit history.'''
    await _call_tool('assign_reviewer', {'repo': repo, 'pr_number': pr_number})


@call_tool_app.command(name='get_morning_briefing')
async def get_morning_briefing(
) -> None:
    '''Get a multi-repo morning briefing aggregating items across all repositories.
Returns Open issues assigned to you, PRs waiting for your review, and the status of PRs you authored.
Call this when the user asks for a dashboard, summary, or morning briefing.'''
    await _call_tool('get_morning_briefing', {})


if __name__ == "__main__":
    app()
